<?php
/*
 * Generated configuration file
 * Generated by: phpMyAdmin 4.8.1 setup script
 * Date: Wed, 30 May 2018 14:52:36 +0000
 */

/* Servers configuration */
$i = 0;

/* Server: CDC [1] */
$i++;
$cfg['Servers'][$i]['verbose'] = 'CDC';
$cfg['Servers'][$i]['host'] = 'cdc-1.jcvi.org';
$cfg['Servers'][$i]['port'] = 3306;
$cfg['Servers'][$i]['socket'] = '';
$cfg['Servers'][$i]['auth_type'] = 'cookie';
$cfg['Servers'][$i]['user'] = 'root';
$cfg['Servers'][$i]['password'] = '';

/* End of servers configuration */

$cfg['blowfish_secret'] = 'GRcg#=a.IIk.hV~rkO3F$K\'.9e6lgh';
$cfg['DefaultLang'] = 'en';
$cfg['ServerDefault'] = 1;
$cfg['UploadDir'] = '';
$cfg['SaveDir'] = '';
?>
