<?php include 'includes/config.inc.php';
echo "create table phylum_country_average (
Body_Site varchar(10),
Country varchar(55),
Saccharibacteria decimal(4,3),
Bacteroidetes decimal(4,3),
Armatimonadetes decimal(4,3),
WCHB1_60 decimal(4,3),
Cyanobacteria decimal(4,3),
Tenericutes decimal(4,3),
Acidobacteria decimal(4,3),
Fusobacteria decimal(4,3),
Gemmatimonadetes decimal(4,3),
Nitrospirae decimal(4,3),
Actinobacteria decimal(4,3),
Fibrobacteres decimal(4,3),
Proteobacteria decimal(4,3),
Spirochaetae decimal(4,3),
Planctomycetes decimal(4,3),
Chloroflexi decimal(4,3),
Firmicutes decimal(4,3),
Gracilibacteria decimal(4,3),
Synergistetes decimal(4,3),
Parcubacteria decimal(4,3),
SHA_109 decimal(4,3),
Deinococcus_Thermus decimal(4,3),
Verrucomicrobia decimal(4,3),
Microgenomates decimal(4,3),
Candidate_division_SR1 decimal(4,3),
Chlorobi decimal(4,3),
Hydrogenedentes decimal(4,3),
unclassified decimal(4,3),
Lentisphaerae decimal(4,3),
Chlamydiae decimal(4,3),
Elusimicrobia decimal(4,3)
)";
>?
