<?php include 'includes/header.php';?>
<script type="text/javascript" language="JavaScript">
function paste_example_prot()
{
	seq_txt_activate();
 document.example.seq.value = ">Test Sequence\nMARKTKQQARETRQLILDVALRLFSQQGVSSTSLATIAKAAGVTRGAIYWHFKNKSDLFNEIWELSDASISDLEIEYRAKFPNDPLSVIREILVYVLEATVTEERRRLMMEIIYHKCEFVGEMTVVQQAQRQLSLASYERIEQTLKECIAAKLLPANLLTRRAAVLMRSYLSGLMENWLFAPDSFDLHAEARDYVAILLEMYQFCPTLRGPESLSA";
}
function paste_example_nucl()
{
	seq_txt_activate();
 document.example.seq.value = ">Test Sequence\nGTGCTGGAAGGACGCATCGTGACAGTCTCGAGTCGGACCGAGTCCCCGCTCGCCGCGCCCGGAGTCCCGGGTGCGCCCCGGCGGCTCTCGTTCGCCAGAATCCGCGAGCCCCTGGCGGTTCCGGGCCTGCTGGACATTCAGACCGAATCGTTCGGGTGGCTGATCGGCGCACCCGACTGGTGCGCCCGCGCGGCAGCCCGCGGGACGGAACCGGTCGCCGGGCTGGCCGAGGTGCTCGCCGAGATCAGCCCCATCGAGGACTTCGCGGGCACGATGTCGCTGACGTTGTCCGATCCGCGGTTCGAGGAGGTCAAGGCCTCCGTCGAGGAGTGCAAGGACAAGGATCTGACCTATGCCGCGCCGTGGTTCGTCACGGCGGAATTCGTGAACAACAACACCGGCGAGATCAAGAGCCAGACCGTTTTCATGGGTGATTTCCCCATGATGACCGCGCACGGGACATTCGTCGTCAACGGCACCGAACGGGTGGTCGTGTCGCAACTGGTGCGCTCGCCGGGCGTGTACTTCGACCACGCGATCGACAAGGGTTCGGAGAAGGACGTGCACAGCGCGCGGGTGATCCCGTCGCGCGGTGCCTGGCTGGAGTTCGACGTCGACAAGCGCGACACCCTGGGCGTGCGCATCGACCGCAAGCGCCGTCAGCCGGTAACGGTGCTGCTCAAGGCGCTGGGCTGGAGTGCGGAGCGAATCGCCGAGCGATTCGGGTTCGCCCCGCTGATCATGGCCTCGCTGGCCAAGGACAACGTGGCGGGCACCGACGACGCTTTGCTCGAGATCCATCGCAAGCTGCGTCCGGGCGAGCCGCCGACCAAGGAGTCGGCACAGAACCTGCTGGCAAATCTGTTCTTCACCGAGAAGCGCTACGACCTGGCGCGGGTGGGCCGTTACAAGATCGACAAGAAGCTCGGGCTGCGCGCTCCGGGGGCACCGCGGGTGCTCACCGAGGACGACATCGCGGCCACCATCGAGTACCTGGTGCGCCTGCACGCCGGGGAGAGGACGATGATCGCGCCCGGCGGGGTCGAGGTGCCGGTGGAGGTCGACGACATCGACCATTTCGGTAACCGCCGGGTGCGCACCGTGGGTGAGCTGATCCAGAACCAGATCCGCGTGGGTCTGTCCCGGATGGAACGGGTGGTGCGGGAGCGCATGACCACCCAGGACGTCGAGGCGATCACGCCGCAGTCGCTGATGAACATCCGCCCGGTGGTCGCGGCGATGAAGGAGTTCTTCGGCACCTCGCAGCTGTCGCAGTTCATGGACCAGCGCAACCCGCTGGCGAGCCTGACCAACAAGCGGCGGCTGTCCGCGCTCGGGCCGGGCGGGCTCTCGCGCGAACGGGCCGGCTTGGAGGTCCGCGACGTGCACTACAGCCACTACGGCCGGATGTGCCCGATCGAGACGCCGGAGGGGCCGAACATCGGCCTGATGGGGTACCTGTCGGTGTACGCGCGGGTCAACCCGTTCGGTTTCGTCGAGACCCCCTACCGGCGGGTGGTGGACGGCCGGGTCACCGACGAGGTCGATTACCTCACCGCCGACGAGGAGGACCGGCACGTGGTGGCCCAGGCGAACGAACCGCTGGACGCCGAGGGCCGCTTCCTGGCCGCGCGAATCCCGGTGCGCCGGAAGAACTCCGAGGTGGAACTCGTCGATTCCGCCGCGGTGGATTACATGGATGTGTCGCCGCGGCAGATGGTGTCGGTGGCGACGGCGATGATTCCGTTCCTCGAGCATGATGATGCCAACCGTGCGCTGATGGGTGCGAATATGCAGCGTCAGGCGGTGCCGTTGATTCGGTCGGAGGCGCCGATCGTGGGTACCGGTATGGAGCTGCGTGCGGCGGTGGATGCCGGTGATGTGGTGGTGAACGAGAAGGCCGGTGTGGTCGAGGAGGTTTCGGCCGATTACGTCACGGTGATGGCCGATGACGGGACTCGTAAGTCGTATCGGATGCGGAAGTTCAACCGGTCGAATCAGGGGACGTGTTCGAATCAGCGGCCGATCGTGGACGAGGGTCAGCGGGTCGAGGCCGGGCAGGTGTTGGCTGATGGGCCGTGCACCGAGAACGGTGAGATGGCGCTGGGTAAGAACCTGTTGGTGGCGATCATGCCGTGGGAGGGGCACAACTACGAGGACGCGATCATCCTGTCGCAGCGGTTGGTGGAGCAGGATGTGTTGACCTCGATCCATATCGAGGAGCACGAGATCGATGCTCGTGACACCAAGCTCGGTGCCGAGGAGATCACTCGCGACATTCCGAATGTCTCCGATGAGGTGTTGGCGGATCTGGACGAGCGTGGCATCGTGCGGATCGGTGCGGAGGTGCGTGATGGTGACATCCTGGTCGGTAAGGTCACGCCCAAGGGTGAGACCGAGCTGACGCCGGAGGAGCGGTTGCTGCGGGCGATCTTCGGGGAGAAGGCGCGTGAGGTGCGTGATACCTCGTTGAAGGTGCCCCACGGTGAGTCGGGCAAGGTCATCGGGATCCGGGTGTTCTCTCGGGAGGACGATGACGATCTGCCGCCCGGTGTCAACGAGTTGGTGCGGGTGTATGTGGCGCAGAAGCGCAAGATCCAAGACGGTGACAAGCTGGCCGGTCGGCACGGGAACAAGGGTGTGATCGGCAAGATCCTGCCCACCGAGGACATGCCGTTCCTGCCCGATGGCACCCCGGTCGACATCATCCTCAACACCCACGGTGTGCCGCGGCGTATGAACATCGGCCAGATCCTGGAAACCCACCTCGGCTGGATCGGCAAAGCCGGCTGGAAGGTCGAGGGCAACCCCGAGTGGGCCAAGGATCTGCCGGAGGAGATGTGGGAGGCCCCCGCGGACTCCAACATCGCGACTCCGGTGTTCGACGGTGCCCGCGAGGAGGAGCTGACGGGTCTGCTGGGCTCGACGCTGCCCAACCGTGACGGTGAGCGGATGGTCGACGACAACGGCAAGGCCGTGCTGTTCGACGGTCGTTCCGGTGAGCCGTTCCCGTACCCGGTGGCGGTGGGCTACATGTACATCCTGAAGCTGCACCACCTGGTCGACGACAAGATCCACGCTCGCTCCACCGGCCCGTACTCGATGATCACCCAGCAGCCGCTCGGTGGTAAGGCCCAGTTCGGTGGCCAGCGCTTCGGTGAGATGGAGTGCTGGGCGATGCAGGCCTACGGCGCGGCCTACACCCTGCAGGAACTGCTCACGATCAAGTCCGACGACGTCGTCGGCCGCGTGAAGGTCTACGAGGCGATCGTCAAGGGCGACAACATCCCGGAACCCGGTGTGCCGGAATCGTTCAAGGTGTTGTTGAAGGAACTCCAGGCACTGTGCCTCAACGTCGAGGTGCTGTCCGCCGGTGCCGCGGTCGAACTGGCGCACGGGGTCGACGACGATCACGAGCGGACGGCCGCGAACCTCGGCATCAACCTGTCCCGCGCCGAATCCATCACGGAGACCGAGCTGTCCGGGTGA";
}

</script>
<script language="JavaScript">
function setVisibility(id, visibility) {
document.getElementById(id).style.display = visibility;
}
</script>
<style type="text/css">
divx {
background-color: #f1f1f1;
color: black;
display: none;
}
.center {
    display: block;
    margin-left: auto;
    margin-right: auto;
    width: 50%;
}
</style>

<section class="main-container">
   <div class="container">
        <div class="row">
            <div class="main col-md-12">
			<h2 class="title">Sequence Similarity Search Module</h2>
		    <div class="separator-2"></div>
 				<div style="line-height: 150%;"> <p style="text-align:justify"; > Perform a nucleotide or protein search using AMR-Finder against the AMRdb. Paste protein or nucleotide sequences in FASTA format. For more information see AMRdb <a href="help.php#sequence_simlarity_search">help page</a></p><hr></hr>
				</div>
				<div class="main col-md-12">
					<form name="example" action="submitseq.php" method="POST" enctype="multipart/form-data" onSubmit="return validateForm()">
					Please paste your sequence in FASTA format to be searched:<br>
					<input type="button" class="btn btn-primary btn-sm" value="use an example protein sequence" onClick="paste_example_prot()">
					<input type="button" class="btn btn-primary btn-sm" value="use an example nucleotide sequence" onClick="paste_example_nucl()"> <br>
					<textarea ALIGN="TOP" ROWS="5" COLS="135" NAME="seq" id ="seq" onclick="seq_txt_activate()"></textarea> 
					<!-- <div class="radio">
									<label>
										<input type="radio" name="db" id="optionsRadios1" value="pr" checked="">
										Peform query against the Protein database
									</label>
					</div>
					<div class="radio">
									<label>
										<input type="radio" name="db" id="optionsRadios2" value="nu">
										Peform query against the Nucleotide database
									</label>
					</div> -->
					 <br>Select File to upload:

	    				<input type="file" name="seq_file" id="seq_file" onclick="seq_file_activate()">
						<br>
						<!-- Please paste sequence in the text box above or upload a sequence file -->
						<br>
					<div class="main col-md-12" align="center">
						<input value="SUBMIT" align="middle" name="method" type="submit" class="btn btn-default" onClick="validate_form()">
					</div>
					</form>
				</div>
 		
			</div>
	    </div>
   </div>  
</section>
<script type="text/javascript">
	function seq_txt_activate(){
		document.getElementById('seq').disabled=false;
		document.getElementById('seq').readOnly =false;
		document.getElementById('seq_file').disabled=true;
	}
		function seq_file_activate(){
		document.getElementById('seq').disabled=true;
		document.getElementById('seq').readOnly =true;
		document.getElementById('seq_file').disabled=false;
	}


</script>
<?php include 'includes/footer.php';?>
